# Generated by Django 4.1.3 on 2022-12-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FreeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("free", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=5000, null=True),
                ),
                ("event_date", models.DateTimeField(blank=True, null=True)),
                (
                    "header_image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("reg_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaidEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("paid", models.CharField(blank=True, max_length=100, null=True)),
                ("price", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "space_capacity",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=5000, null=True),
                ),
                ("event_date", models.DateTimeField(blank=True, null=True)),
                ("event_end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "header_image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
            ],
        ),
    ]
