# Generated by Django 4.1.3 on 2022-12-13 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AdminSection", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event", old_name="header_image", new_name="header_images",
        ),
    ]
