# Generated by Django 4.1.3 on 2022-12-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AdminSection", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="FreeEvent", new_name="Free",),
    ]
