# Generated by Django 4.1.3 on 2023-01-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminSection", "0003_slot"),
    ]

    operations = [
        migrations.DeleteModel(name="Slot",),
        migrations.AlterField(
            model_name="event", name="slot_left", field=models.IntegerField(default=0),
        ),
    ]
