# Generated by Django 4.1.3 on 2022-12-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminSection", "0003_rename_paidevent_event_delete_free"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
