# Generated by Django 4.1.3 on 2022-12-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminSection", "0004_alter_event_event_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
