# Generated by Django 4.1.3 on 2023-01-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminSection", "0005_rename_slot_left_event_bookings"),
    ]

    operations = [
        migrations.AddField(
            model_name="event", name="slot_left", field=models.IntegerField(default=0),
        ),
    ]
