# Generated by Django 4.1.3 on 2023-01-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminSection", "0007_alter_event_space_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="event", name="days_left", field=models.IntegerField(default=0),
        ),
    ]
