# Generated by Django 4.1.3 on 2023-01-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminSection", "0008_event_days_left"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="days_left",),
        migrations.AddField(
            model_name="event",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
