# Generated by Django 4.1.3 on 2023-01-02 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AdminSection", "0009_remove_event_days_left_event_is_cancelled"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="is_cancelled",),
    ]
