# Generated by Django 4.1.3 on 2023-01-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminSection", "0010_remove_event_is_cancelled"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
