# Generated by Django 4.1.3 on 2023-01-06 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AdminSection", "0014_rename_phone_number_customer_phone"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="paid",),
    ]
