# Generated by Django 4.1.3 on 2023-01-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "AdminSection",
            "0016_customer_amount_customer_date_created_customer_ref_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(name="customer", options={"ordering": ()},),
        migrations.AddField(
            model_name="customer",
            name="event_name",
            field=models.CharField(
                blank=True, default="False", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="customer", name="amount", field=models.PositiveIntegerField(),
        ),
    ]
