# Generated by Django 4.1.3 on 2023-01-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminSection", "0017_alter_customer_options_customer_event_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="event_name",
            field=models.CharField(max_length=100),
        ),
    ]
