# Generated by Django 4.1.3 on 2023-01-12 13:18

import AdminSection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminSection", "0020_customer_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="location",
            field=models.CharField(
                max_length=100, verbose_name=AdminSection.models.Event
            ),
        ),
    ]
