# Generated by Django 4.1.3 on 2023-01-13 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AdminSection", "0021_alter_customer_location"),
    ]

    operations = [
        migrations.RemoveField(model_name="customer", name="location",),
    ]
