# Generated by Django 4.1.3 on 2023-01-19 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AdminSection", "0023_place_restaurant_waiter"),
    ]

    operations = [
        migrations.RemoveField(model_name="restaurant", name="place",),
        migrations.RemoveField(model_name="waiter", name="restaurant",),
        migrations.DeleteModel(name="Place",),
        migrations.DeleteModel(name="Restaurant",),
        migrations.DeleteModel(name="Waiter",),
    ]
