# Generated by Django 4.1.3 on 2023-01-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "AdminSection",
            "0024_remove_restaurant_place_remove_waiter_restaurant_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="time_field",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
