# Generated by Django 4.1.3 on 2023-01-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminSection", "0025_event_time_field"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="time_field",),
        migrations.AlterField(
            model_name="event",
            name="event_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
