# Generated by Django 4.1.3 on 2023-01-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminSection", "0027_alter_event_event_date_alter_event_event_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="amount",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
