# Generated by Django 4.1.3 on 2023-02-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminSection", "0028_alter_customer_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
